name: CI

on:
  push:
    branches:
      - main

env:
  FILE_PATH_VERSION_INFO: ./src/utils/version/VersionInfo.ts

jobs:
  build:
    name: Build 🏗️
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

      - name: Version Info 💉
        run: |
          COMMIT=$GITHUB_SHA
          BRANCH=${GITHUB_REF#refs/heads/}
          TAG=''
          if [[ ${{ github.ref_type }} == 'tag' ]]; then
            TAG=${GITHUB_REF#refs/tags/}
          fi
          echo "write tag, branch & commit id to $FILE_PATH_VERSION_INFO"
          echo "export const VersionInfo = { tag: '$TAG', branch: '$BRANCH', commit: '$COMMIT' };" > $FILE_PATH_VERSION_INFO
          cat $FILE_PATH_VERSION_INFO

      - name: Build 🏗️
        run: npm run build

  lint:
    name: Lint ✅
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

      - name: Lint ✅
        run: npm run lint

  tsc:
    name: TypeScript Compiler 🔎
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

      - name: TypeScript Compiler 🔎
        run: npm run tsc

  npm-release:
    name: npm release 📦
    needs: [build, lint, tsc]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

      - name: Export tRPC API 🏗️
        run: npm run trpc-api-export

      - name: npm release 📦
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release

  # deploy:
  #   name: Deploy 🚀
  #   needs: [build, lint, tsc]
  #   runs-on: ubuntu-latest

  #   environment:
  #     name: tRPC API
  #     url: https://trpc-api-boilerplate.onrender.com

  #   steps:
  #     - name: Deploy 🚀
  #       uses: fjogeleit/http-request-action@v1
  #       with:
  #         url: ${{ secrets.RENDER_DEPLOY_HOOK }}
  #         method: 'GET'
